{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Self","kind":"typeIdentifier"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/MediaErrorEvent\/errorDescription(_:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/snowplowtracker\/mediaerrorevent\/errordescription(_:)"]}],"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/MediaErrorEvent"]]},"abstract":[{"text":"Longer description for the error that occurred in the playback.","type":"text"}],"metadata":{"modules":[{"name":"SnowplowTracker"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"text":"Self","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@SnowplowTracker@objc(cs)SPMediaErrorEvent(im)errorDescription:","title":"errorDescription(_:)"},"kind":"symbol","references":{"doc://SnowplowTracker/documentation/SnowplowTracker":{"type":"topic","url":"\/documentation\/snowplowtracker","title":"SnowplowTracker","abstract":[],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","role":"collection","kind":"symbol"},"doc://SnowplowTracker/documentation/SnowplowTracker/MediaErrorEvent/errorDescription(_:)":{"title":"errorDescription(_:)","abstract":[{"type":"text","text":"Longer description for the error that occurred in the playback."}],"url":"\/documentation\/snowplowtracker\/mediaerrorevent\/errordescription(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?) -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/MediaErrorEvent\/errorDescription(_:)"},"doc://SnowplowTracker/documentation/SnowplowTracker/MediaErrorEvent":{"kind":"symbol","url":"\/documentation\/snowplowtracker\/mediaerrorevent","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/MediaErrorEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MediaErrorEvent","kind":"identifier"}],"title":"MediaErrorEvent","type":"topic","abstract":[{"type":"text","text":"Media player event tracked when the resource could not be loaded due to an error."}],"role":"symbol","navigatorTitle":[{"text":"MediaErrorEvent","kind":"identifier"}]}}}