{"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/MediaErrorEvent\/errorDescription(_:)"},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorDescription"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?) -> "},{"text":"Self","kind":"typeIdentifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/MediaErrorEvent"]]},"abstract":[{"type":"text","text":"Longer description for the error that occurred in the playback."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/snowplowtracker\/mediaerrorevent\/errordescription(_:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"errorDescription(_:)","symbolKind":"method","role":"symbol","externalID":"c:@M@SnowplowTracker@objc(cs)SPMediaErrorEvent(im)errorDescription:","modules":[{"name":"SnowplowTracker"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Self"}]},"references":{"doc://SnowplowTracker/documentation/SnowplowTracker/MediaErrorEvent/errorDescription(_:)":{"kind":"symbol","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/MediaErrorEvent\/errorDescription(_:)","url":"\/documentation\/snowplowtracker\/mediaerrorevent\/errordescription(_:)","abstract":[{"type":"text","text":"Longer description for the error that occurred in the playback."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Self"}],"title":"errorDescription(_:)","type":"topic","role":"symbol"},"doc://SnowplowTracker/documentation/SnowplowTracker":{"url":"\/documentation\/snowplowtracker","role":"collection","abstract":[],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","type":"topic","title":"SnowplowTracker","kind":"symbol"},"doc://SnowplowTracker/documentation/SnowplowTracker/MediaErrorEvent":{"abstract":[{"type":"text","text":"Media player event tracked when the resource could not be loaded due to an error."}],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/MediaErrorEvent","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MediaErrorEvent","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MediaErrorEvent"}],"kind":"symbol","title":"MediaErrorEvent","role":"symbol","type":"topic","url":"\/documentation\/snowplowtracker\/mediaerrorevent"}}}