{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Instance Method","title":"errorDescription(_:)","symbolKind":"method","modules":[{"name":"SnowplowTracker"}],"externalID":"c:@M@SnowplowTracker@objc(cs)SPMediaErrorEvent(im)errorDescription:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorDescription"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/MediaErrorEvent"]]},"abstract":[{"type":"text","text":"Longer description for the error that occurred in the playback."}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/MediaErrorEvent\/errorDescription(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorDescription"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Self"}],"languages":["swift"],"platforms":["macOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/snowplowtracker\/mediaerrorevent\/errordescription(_:)"]}],"references":{"doc://SnowplowTracker/documentation/SnowplowTracker":{"title":"SnowplowTracker","role":"collection","url":"\/documentation\/snowplowtracker","type":"topic","kind":"symbol","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","abstract":[]},"doc://SnowplowTracker/documentation/SnowplowTracker/MediaErrorEvent":{"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/MediaErrorEvent","url":"\/documentation\/snowplowtracker\/mediaerrorevent","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MediaErrorEvent","kind":"identifier"}],"kind":"symbol","title":"MediaErrorEvent","navigatorTitle":[{"text":"MediaErrorEvent","kind":"identifier"}],"abstract":[{"type":"text","text":"Media player event tracked when the resource could not be loaded due to an error."}]},"doc://SnowplowTracker/documentation/SnowplowTracker/MediaErrorEvent/errorDescription(_:)":{"abstract":[{"type":"text","text":"Longer description for the error that occurred in the playback."}],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/MediaErrorEvent\/errorDescription(_:)","kind":"symbol","title":"errorDescription(_:)","url":"\/documentation\/snowplowtracker\/mediaerrorevent\/errordescription(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"role":"symbol"}}}