{"metadata":{"modules":[{"name":"SnowplowTracker"}],"role":"symbol","externalID":"c:@M@SnowplowTracker@objc(cs)SPMediaErrorEvent(im)errorDescription:","symbolKind":"method","roleHeading":"Instance Method","title":"errorDescription(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}]},"abstract":[{"text":"Longer description for the error that occurred in the playback.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}]}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/MediaErrorEvent"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/MediaErrorEvent\/errorDescription(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/snowplowtracker\/mediaerrorevent\/errordescription(_:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://SnowplowTracker/documentation/SnowplowTracker/MediaErrorEvent/errorDescription(_:)":{"url":"\/documentation\/snowplowtracker\/mediaerrorevent\/errordescription(_:)","kind":"symbol","abstract":[{"type":"text","text":"Longer description for the error that occurred in the playback."}],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/MediaErrorEvent\/errorDescription(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Self"}],"role":"symbol","type":"topic","title":"errorDescription(_:)"},"doc://SnowplowTracker/documentation/SnowplowTracker/MediaErrorEvent":{"title":"MediaErrorEvent","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MediaErrorEvent","kind":"identifier"}],"abstract":[{"text":"Media player event tracked when the resource could not be loaded due to an error.","type":"text"}],"url":"\/documentation\/snowplowtracker\/mediaerrorevent","navigatorTitle":[{"kind":"identifier","text":"MediaErrorEvent"}],"role":"symbol","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/MediaErrorEvent"},"doc://SnowplowTracker/documentation/SnowplowTracker":{"title":"SnowplowTracker","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","role":"collection","kind":"symbol","url":"\/documentation\/snowplowtracker","type":"topic","abstract":[]}}}