{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)message","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"roleHeading":"Instance Property","modules":[{"name":"SnowplowTracker"}],"role":"symbol","title":"message"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/message"},"abstract":[{"type":"text","text":"Message of the error."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"message"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"languages":["swift"],"platforms":["macOS"]}]}],"variants":[{"paths":["\/documentation\/snowplowtracker\/trackererror\/message"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"kind":"symbol","url":"\/documentation\/snowplowtracker\/trackererror","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TrackerError","kind":"identifier"}],"title":"TrackerError","type":"topic","abstract":[{"text":"Tracker error event used in diagnostic autotracking.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"TrackerError","kind":"identifier"}]},"doc://SnowplowTracker/documentation/SnowplowTracker":{"type":"topic","url":"\/documentation\/snowplowtracker","title":"SnowplowTracker","abstract":[],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","role":"collection","kind":"symbol"},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/message":{"type":"topic","abstract":[{"type":"text","text":"Message of the error."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"message"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/message","kind":"symbol","title":"message","url":"\/documentation\/snowplowtracker\/trackererror\/message","role":"symbol"}}}